"""Write config.toml from setup results.

Never writes bot token to the file — only the env var name.
"""

from __future__ import annotations

from pathlib import Path

from factorylm.setup.discord_setup import SetupResult

DEFAULT_OUTPUT = Path("~/.factorylm/config.toml").expanduser()

# Agent channels that map to agent configs
AGENT_CHANNELS = {"tony", "ultron", "jarvis", "hetzner"}


def write_config(
    result: SetupResult,
    output_path: str | Path | None = None,
) -> Path:
    """Write a valid config.toml from setup results.

    Args:
        result: SetupResult from DiscordSetup.run_setup().
        output_path: Where to write. Defaults to ~/.factorylm/config.toml.

    Returns:
        The path written to.
    """
    path = Path(output_path) if output_path else DEFAULT_OUTPUT
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# FactoryLM Discord Layer config",
        "# Generated by factorylm-setup — edit as needed",
        "# Bot token is read from env var, NEVER stored here",
        "",
        "[discord]",
        f'guild_id = {result.guild_id}',
        'bot_token_env_var = "DISCORD_BOT_TOKEN"',
        "",
    ]

    for agent_name in sorted(AGENT_CHANNELS & set(result.channels)):
        ch_id = result.channels.get(agent_name, 0)
        webhook = result.webhooks.get(agent_name, "")
        lines.extend([
            f"[discord.agents.{agent_name}]",
            f'name = "{agent_name.capitalize()}"',
            f'webhook_url = "{webhook}"',
            f"channel_id = {ch_id}",
            "",
        ])

    lines.extend([
        "[telegram]",
        'token_env_var = "TELEGRAM_BOT_TOKEN"',
        "chat_id = 0",
        "",
        "[relay]",
        'host = "127.0.0.1"',
        "port = 8765",
        'log_level = "INFO"',
        "",
    ])

    path.write_text("\n".join(lines))
    return path
