"""CMMS adapter — bidirectional sync via GitHub Gist.

Pushes MES work orders to GitHub Gists as portable CMMS documents
(Markdown + CSV). Any CMMS that can import CSV can consume these.

Uses the same document schema as cmms/gist_work_order.py but calls
the GitHub API directly via httpx (no subprocess / gh CLI dependency).

Controlled by settings.cmms_enabled:
  False (default) — push_work_order() returns a synthetic response.
                    Safe for tests and environments without a GitHub token.
  True            — calls the real GitHub Gist API. Requires
                    settings.cmms_github_token (GitHub PAT, gist scope).

CSV columns match cmms/gist_work_order.py CSV_COLUMNS for compatibility.
"""

import csv
import io
import logging
from datetime import datetime, timezone
from typing import Optional

import httpx

from backend.config import settings

logger = logging.getLogger(__name__)

_GITHUB_GIST_API = "https://api.github.com/gists"

# CSV schema — matches cmms/gist_work_order.py for cross-tool compat
_CSV_COLUMNS = [
    "work_order_id", "title", "status", "priority", "asset_name",
    "asset_id", "location", "site", "assigned_to", "assigned_team",
    "work_type", "category", "due_date", "created_date", "completed_date",
    "completed_by", "reported_by", "channel", "estimated_hours", "cost",
    "completion_notes", "failure_code", "description", "cmms_system",
    "cmms_external_id",
]


# ── Formatting ────────────────────────────────────────────────────────────────

def format_work_order(
    order_number: str,
    status: str,
    target_qty: int,
    good_qty: int,
    line_name: str,
    line_isa95_path: str,
    product_sku: str,
    product_name: str,
    notes: Optional[str] = None,
    actual_start: Optional[datetime] = None,
    actual_end: Optional[datetime] = None,
    cmms_external_id: Optional[str] = None,
) -> dict:
    """Map MES work order fields to CMMS Gist metadata dict (pure function)."""
    title = f"{product_name} — {line_name}"
    return {
        "work_order_id":    order_number,
        "title":            title,
        "status":           status.lower(),
        "priority":         "normal",
        "asset_name":       line_name,
        "asset_id":         line_isa95_path,
        "location":         line_isa95_path,
        "site":             "Lake Wales, FL",
        "assigned_to":      "",
        "assigned_team":    "Production",
        "work_type":        "Production",
        "category":         "Manufacturing",
        "due_date":         "",
        "created_date":     datetime.now(timezone.utc).isoformat(),
        "completed_date":   actual_end.isoformat() if actual_end else "",
        "completed_by":     "",
        "reported_by":      "MIRA MES",
        "channel":          "MES API",
        "estimated_hours":  str(round(target_qty / 3600, 2)),  # rough estimate
        "cost":             "",
        "completion_notes": notes or "",
        "failure_code":     "",
        "description":      (
            f"Production run: {target_qty} units of {product_sku} ({product_name}) "
            f"on {line_name}. Good parts: {good_qty}."
        ),
        "cmms_system":      "FactoryLM MES",
        "cmms_external_id": cmms_external_id or "",
    }


def _render_md(metadata: dict) -> str:
    """Render minimal Markdown work order document."""
    return f"""# Work Order: {metadata['work_order_id']}

**Title:** {metadata['title']}
**Status:** {metadata['status']}
**Priority:** {metadata['priority']}
**Asset:** {metadata['asset_name']} (`{metadata['asset_id']}`)
**Site:** {metadata['site']}
**Team:** {metadata['assigned_team']}
**Work Type:** {metadata['work_type']}
**Created:** {metadata['created_date']}
**Completed:** {metadata.get('completed_date') or '—'}
**Reported by:** {metadata['reported_by']}
**System:** {metadata['cmms_system']}

## Description

{metadata['description']}

## Notes

{metadata.get('completion_notes') or '—'}

---
*Generated by FactoryLM MES — {metadata['site']}*
"""


def _render_csv(metadata: dict) -> str:
    """Render CSV with header + one data row."""
    buf = io.StringIO(newline="")
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(_CSV_COLUMNS)
    writer.writerow([metadata.get(col, "") for col in _CSV_COLUMNS])
    return buf.getvalue()


def _gist_files(metadata: dict) -> dict:
    """Build the Gist files payload for the GitHub API."""
    return {
        "work-order.md":  {"content": _render_md(metadata)},
        "work-order.csv": {"content": _render_csv(metadata)},
    }


# ── GitHub Gist API ───────────────────────────────────────────────────────────

def push_work_order(metadata: dict, gist_id: Optional[str] = None) -> dict:
    """Create or update a GitHub Gist for a CMMS work order.

    Args:
        metadata: Output of format_work_order().
        gist_id:  If provided, PATCH the existing Gist; otherwise POST a new one.

    Returns:
        {"gist_id": str, "gist_url": str}

    When settings.cmms_enabled is False, returns a synthetic response and
    makes no HTTP calls — safe for tests and non-CMMS environments.
    """
    if not settings.cmms_enabled:
        synthetic_id = f"mock-{metadata['work_order_id'].lower().replace('-', '')}"
        logger.info("CMMS disabled — synthetic push for %s", metadata["work_order_id"])
        return {
            "gist_id":  gist_id or synthetic_id,
            "gist_url": f"https://gist.github.com/{gist_id or synthetic_id}",
        }

    if not settings.cmms_github_token:
        raise RuntimeError("cmms_enabled=True but cmms_github_token is empty")

    headers = {
        "Authorization": f"Bearer {settings.cmms_github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    files   = _gist_files(metadata)
    wo_id   = metadata["work_order_id"]
    description = f"[FactoryLM MES] {wo_id} — {metadata['title']}"

    with httpx.Client(timeout=10.0) as client:
        if gist_id:
            # Update existing Gist
            resp = client.patch(
                f"{_GITHUB_GIST_API}/{gist_id}",
                headers=headers,
                json={"description": description, "files": files},
            )
        else:
            # Create new Gist
            resp = client.post(
                _GITHUB_GIST_API,
                headers=headers,
                json={"description": description, "files": files, "public": False},
            )

    resp.raise_for_status()
    data = resp.json()
    result = {"gist_id": data["id"], "gist_url": data["html_url"]}
    logger.info("CMMS Gist %s: %s", "updated" if gist_id else "created", result["gist_url"])
    return result
