"""
THE WEAVER - Celery Tasks
=========================
Generates documentation and procedures.
Converted from HTTP server (port 8093) to Celery worker.
"""

import sys
sys.path.insert(0, '/opt/master_of_puppets')
from celery_app import app
from workers.base_worker import BaseAgent, with_token_tracking, with_celery_tracing
from observability import traced, track_llm_call, track_api_call


class Weaver(BaseAgent):
    """Generates documentation and procedures."""
    
    def __init__(self):
        super().__init__("Weaver")
    
    def generate_documentation(self, topic: str, context: dict = None) -> dict:
        """Generate documentation for a topic."""
        self.logger.info(f"Generating docs for: {topic}")
        
        # TODO: Integrate with AI for document generation
        return {
            "topic": topic,
            "context": context,
            "content": f"# {topic}\n\nDocumentation pending AI integration.",
            "format": "markdown"
        }
    
    def create_procedure(self, title: str, steps: list) -> dict:
        """Create a standard operating procedure."""
        self.logger.info(f"Creating procedure: {title}")
        
        return {
            "title": title,
            "steps": steps,
            "format": "markdown",
            "content": f"# {title}\n\n" + "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps))
        }


weaver = Weaver()


@app.task(bind=True, name='weaver.generate_documentation')
@with_token_tracking('weaver')
def generate_documentation(self, topic: str, context: dict = None) -> dict:
    """Generate documentation for a topic."""
    weaver.log_start('generate_documentation', topic=topic)
    
    try:
        result = weaver.generate_documentation(topic, context)
        weaver.log_complete('generate_documentation', result)
        return result
    except Exception as e:
        weaver.log_error('generate_documentation', e)
        raise


@app.task(bind=True, name='weaver.create_procedure')
@with_token_tracking('weaver')
def create_procedure(self, title: str, steps: list) -> dict:
    """Create a standard operating procedure."""
    weaver.log_start('create_procedure', title=title)
    
    try:
        result = weaver.create_procedure(title, steps)
        weaver.log_complete('create_procedure', result)
        return result
    except Exception as e:
        weaver.log_error('create_procedure', e)
        raise


@app.task(bind=True, name='weaver.health')
@with_celery_tracing("health")
@traced(name="health", layer="execution")
def health(self) -> dict:
    """Health check."""
    return {"status": "ok", "agent": "Weaver"}


@app.task(bind=True, name='weaver.generate_report')
@with_token_tracking('weaver')
def generate_report(self, task_spec: dict) -> dict:
    """
    Generate a report based on task specification.
    Used by Monkey dispatcher for report tasks from Jira.
    """
    weaver.log_start('generate_report', jira_key=task_spec.get('jira_key'))
    
    summary = task_spec.get("summary", "Report")
    description = task_spec.get("description", "")
    
    # TODO: Integrate with AI for actual report generation
    # For now, create a template report
    
    content = f"""# Report: {summary}

## Overview
This report was automatically generated by The Weaver.

## Details
{description if description else "No additional details provided."}

## Recommendations
- Review the data and take appropriate action
- Update relevant documentation
- Schedule follow-up if needed

---
*Generated by Master of Puppets - The Weaver*
*Date: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
    
    result = {
        "summary": f"Report generated for: {summary}",
        "content": content,
        "format": "markdown",
        "tokens_used": 0,  # No AI used yet
    }
    
    weaver.log_complete('generate_report', result)
    return result


# ============== REPORT OUTPUT TO SYNC FOLDER ==============

REPORTS_OUTPUT = "/opt/factorylm-sync/automatons-output/reports"
import os
from pathlib import Path
Path(REPORTS_OUTPUT).mkdir(parents=True, exist_ok=True)


@app.task(bind=True, name='weaver.generate_drift_report')
@with_token_tracking('weaver')
def generate_drift_report(self, alert_data: dict) -> dict:
    """
    Generate a drift report and save to sync folder.
    Auto-syncs to all connected devices.
    """
    from datetime import datetime
    
    weaver.log_start('generate_drift_report', metric=alert_data.get('metric'))
    
    metric = alert_data.get('metric', 'unknown')
    sigma = alert_data.get('drift_sigma', 0)
    severity = alert_data.get('severity', 'warning')
    vendor = alert_data.get('vendor', 'unknown')
    plc_ip = alert_data.get('plc_ip', '')
    current = alert_data.get('current_value', 'N/A')
    baseline = alert_data.get('baseline_mean', 'N/A')
    timestamp = datetime.now()
    
    # Generate markdown report
    report_content = f"""# Drift Alert Report

## Summary
- **Metric:** {metric}
- **Severity:** {severity.upper()}
- **Drift Magnitude:** {sigma:.2f}σ from baseline

## Details
| Field | Value |
|-------|-------|
| Vendor | {vendor} |
| PLC IP | {plc_ip} |
| Current Value | {current} |
| Baseline Mean | {baseline} |
| Detection Time | {timestamp.strftime('%Y-%m-%d %H:%M:%S')} |

## Analysis
This drift event was automatically detected by the Master of Puppets drift detection system.
A deviation of {sigma:.1f} standard deviations from the established baseline was observed.

### Recommended Actions
1. Investigate the {metric} sensor/signal
2. Check for environmental changes or equipment modifications
3. Review maintenance history for related components
4. Update baseline if drift represents new normal operating conditions

---
*Generated by The Weaver | Master of Puppets Industrial AI*
*Report ID: DRIFT-{timestamp.strftime('%Y%m%d-%H%M%S')}-{metric[:10]}*
"""
    
    # Save report
    filename = f"drift-report-{timestamp.strftime('%Y%m%d-%H%M%S')}-{metric.replace('/', '-')}.md"
    filepath = os.path.join(REPORTS_OUTPUT, filename)
    
    with open(filepath, 'w') as f:
        f.write(report_content)
    
    result = {
        "summary": f"Generated drift report for {metric}",
        "filepath": filepath,
        "filename": filename,
        "syncs_to": "all connected devices via Syncthing",
        "tokens_used": 0,
    }
    
    weaver.log_complete('generate_drift_report', result)
    return result


@app.task(bind=True, name='weaver.generate_daily_summary')
@with_token_tracking('weaver')
def generate_daily_summary(self) -> dict:
    """
    Generate daily system summary report.
    Called by Celery Beat at end of day.
    """
    from datetime import datetime, timedelta
    import json
    
    weaver.log_start('generate_daily_summary')
    
    timestamp = datetime.now()
    yesterday = timestamp - timedelta(days=1)
    
    # Gather stats from various sources
    # TODO: Pull actual stats from state files
    
    report_content = f"""# Daily System Summary

## Overview
**Report Date:** {timestamp.strftime('%Y-%m-%d')}
**Period:** {yesterday.strftime('%Y-%m-%d')} to {timestamp.strftime('%Y-%m-%d')}

## System Health
- All collectors: Running
- All workers: Active
- Celery Beat: Scheduling tasks

## Activity Summary
- Drift checks performed: [check state files]
- Work orders created: [check postgres]
- Photos analyzed: [check photo analyzer state]
- Documents indexed: [check manual hunter]

## Alerts
Check the work_orders table for any open items requiring attention.

---
*Generated by The Weaver | Master of Puppets Industrial AI*
*Daily Summary ID: DAILY-{timestamp.strftime('%Y%m%d')}*
"""
    
    filename = f"daily-summary-{timestamp.strftime('%Y%m%d')}.md"
    filepath = os.path.join(REPORTS_OUTPUT, filename)
    
    with open(filepath, 'w') as f:
        f.write(report_content)
    
    result = {
        "summary": f"Generated daily summary for {timestamp.strftime('%Y-%m-%d')}",
        "filepath": filepath,
        "tokens_used": 0,
    }
    
    weaver.log_complete('generate_daily_summary', result)
    return result
