"""Write config.toml from setup results.

Never writes bot token to the file — only the env var name.
"""

from __future__ import annotations

import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

from factorylm.setup.discord_setup import SetupResult

DEFAULT_OUTPUT = Path("~/.factorylm/config.toml").expanduser()

# Agent channels that map to agent configs
AGENT_CHANNELS = {"tony", "ultron", "jarvis", "hetzner"}

# Instance metadata
INSTANCE_META: dict[str, dict[str, str]] = {
    "oc_macaroni": {"machine": "Mac Mini (100.108.19.94)", "role": "Boss agent, coordinator"},
    "ultron": {"machine": "DO VPS (100.68.120.99)", "role": "Cloud reasoning, web research"},
    "jarvis-local": {"machine": "Travel Laptop (100.83.251.23)", "role": "PLC/Modbus edge compute"},
    "hetzner": {
        "machine": "Hetzner (100.67.25.53)",
        "role": "Batch compute, large model inference",
    },
    "jarvis-legacy": {"machine": "Legacy", "role": "Legacy operations"},
}


def write_config(
    result: SetupResult,
    output_path: str | Path | None = None,
) -> Path:
    """Write a valid config.toml from setup results.

    Args:
        result: SetupResult from DiscordSetup.run_setup().
        output_path: Where to write. Defaults to ~/.factorylm/config.toml.

    Returns:
        The path written to.
    """
    path = Path(output_path) if output_path else DEFAULT_OUTPUT
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# FactoryLM Discord Layer config",
        "# Generated by factorylm-setup — edit as needed",
        "# Bot token is read from env var, NEVER stored here",
        "",
        "[discord]",
        f'guild_id = {result.guild_id}',
        'bot_token_env_var = "DISCORD_BOT_TOKEN"',
        "",
    ]

    for agent_name in sorted(AGENT_CHANNELS & set(result.channels)):
        ch_id = result.channels.get(agent_name, 0)
        webhook = result.webhooks.get(agent_name, "")
        lines.extend([
            f"[discord.agents.{agent_name}]",
            f'name = "{agent_name.capitalize()}"',
            f'webhook_url = "{webhook}"',
            f"channel_id = {ch_id}",
            "",
        ])

    lines.extend([
        "[telegram]",
        'token_env_var = "TELEGRAM_BOT_TOKEN"',
        "chat_id = 0",
        "",
        "[relay]",
        'host = "127.0.0.1"',
        "port = 8765",
        'log_level = "INFO"',
        "",
    ])

    path.write_text("\n".join(lines))
    return path


def write_instance_config(
    result: SetupResult,
    instance_name: str,
    output_path: str | Path | None = None,
    bot_token_env_var: str = "DISCORD_BOT_TOKEN",
) -> Path:
    """Merge an instance section into existing config.toml.

    Reads the existing config, adds/updates [discord.instances.<name>],
    then writes back. Creates the file with defaults if it doesn't exist.

    Args:
        result: SetupResult from DiscordSetup.run_setup().
        instance_name: Instance key (e.g. "ultron", "jarvis-local").
        output_path: Where to write. Defaults to ~/.factorylm/config.toml.
        bot_token_env_var: Env var name for this instance's bot token.

    Returns:
        The path written to.
    """
    path = Path(output_path) if output_path else DEFAULT_OUTPUT
    path.parent.mkdir(parents=True, exist_ok=True)

    # Load existing config or start fresh
    existing: dict = {}
    if path.exists():
        with open(path, "rb") as f:
            existing = tomllib.load(f)

    # Ensure top-level sections exist
    discord_section = existing.setdefault("discord", {})
    instances = discord_section.setdefault("instances", {})

    # Build instance data
    meta = INSTANCE_META.get(instance_name, {})
    instance_data: dict = {
        "name": instance_name,
        "guild_id": result.guild_id,
        "bot_token_env_var": bot_token_env_var,
        "machine": meta.get("machine", ""),
        "role": meta.get("role", ""),
        "agents": {},
    }

    # Map agent channels to agent configs
    for agent_name in sorted(AGENT_CHANNELS & set(result.channels)):
        ch_id = result.channels.get(agent_name, 0)
        webhook = result.webhooks.get(agent_name, "")
        instance_data["agents"][agent_name] = {
            "name": agent_name.capitalize(),
            "webhook_url": webhook,
            "channel_id": ch_id,
            "machine": meta.get("machine", ""),
            "role": meta.get("role", ""),
        }

    instances[instance_name] = instance_data

    # Write back as TOML (manual serialization — tomllib is read-only)
    _write_toml(existing, path)
    return path


def _write_toml(data: dict, path: Path) -> None:
    """Serialize config dict to TOML format and write to path."""
    lines: list[str] = [
        "# FactoryLM Discord Layer config",
        "# Generated by factorylm-setup — edit as needed",
        "# Bot token is read from env var, NEVER stored here",
        "",
    ]

    discord = data.get("discord", {})

    # [discord] top-level
    lines.append("[discord]")
    if "guild_id" in discord:
        lines.append(f"guild_id = {discord['guild_id']}")
    if "bot_token_env_var" in discord:
        lines.append(f'bot_token_env_var = "{discord["bot_token_env_var"]}"')
    lines.append("")

    # [discord.agents.*] (legacy top-level agents)
    for agent_name, agent_cfg in sorted(discord.get("agents", {}).items()):
        lines.append(f"[discord.agents.{agent_name}]")
        _write_agent_lines(lines, agent_cfg)
        lines.append("")

    # [discord.instances.*]
    for inst_name, inst_cfg in sorted(discord.get("instances", {}).items()):
        lines.append(f"[discord.instances.{inst_name}]")
        lines.append(f'name = "{inst_cfg.get("name", inst_name)}"')
        lines.append(f'guild_id = {inst_cfg.get("guild_id", 0)}')
        token_var = inst_cfg.get("bot_token_env_var", "DISCORD_BOT_TOKEN")
        lines.append(f'bot_token_env_var = "{token_var}"')
        if inst_cfg.get("machine"):
            lines.append(f'machine = "{inst_cfg["machine"]}"')
        if inst_cfg.get("role"):
            lines.append(f'role = "{inst_cfg["role"]}"')
        lines.append("")

        # Instance agents
        for agent_name, agent_cfg in sorted(inst_cfg.get("agents", {}).items()):
            lines.append(f"[discord.instances.{inst_name}.agents.{agent_name}]")
            _write_agent_lines(lines, agent_cfg)
            lines.append("")

    # [telegram]
    telegram = data.get("telegram", {})
    lines.append("[telegram]")
    lines.append(f'token_env_var = "{telegram.get("token_env_var", "TELEGRAM_BOT_TOKEN")}"')
    lines.append(f'chat_id = {telegram.get("chat_id", 0)}')
    lines.append("")

    # [relay]
    relay = data.get("relay", {})
    lines.append("[relay]")
    lines.append(f'host = "{relay.get("host", "127.0.0.1")}"')
    lines.append(f'port = {relay.get("port", 8765)}')
    lines.append(f'log_level = "{relay.get("log_level", "INFO")}"')
    lines.append("")

    path.write_text("\n".join(lines))


def _write_agent_lines(lines: list[str], agent_cfg: dict) -> None:
    """Append TOML lines for an agent config dict."""
    lines.append(f'name = "{agent_cfg.get("name", "")}"')
    lines.append(f'webhook_url = "{agent_cfg.get("webhook_url", "")}"')
    lines.append(f'channel_id = {agent_cfg.get("channel_id", 0)}')
    if agent_cfg.get("machine"):
        lines.append(f'machine = "{agent_cfg["machine"]}"')
    if agent_cfg.get("role"):
        lines.append(f'role = "{agent_cfg["role"]}"')
